name: CI (Test and Upload for Deployment)

on:
  push:
    branches: [ development ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    permissions:
      # Required for deployment actions
      pages: write
      id-token: write 
    steps:
      # ... (Run Tests steps are the same) ...

      - name: Prepare the deployment folder
        run: |
          mkdir sites
          mv htmlcov sites/
          mv coverage.xml sites/

      # Use the Pages Artifact Uploader here. This stages the files.
      - name: Stage Deployment Artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./sites
          
      # REMOVE: actions/upload-artifact@v4
